service: serverless-flask
plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 's3:*'
        - 's3:ListBucket'
        - 's3:GetBucketLocation'
        - 's3:GetObject'
      Resource:
        - 'arn:aws:s3:::demo-s3-bucket-cs493-2'
        - 'arn:aws:s3:::demo-s3-bucket-cs493-2/*'
functions:
  app:
    handler: wsgi.handler
    events:
      - http:
          path: /
          method: get
          cors: true
